// <auto-generated />
using System;
using App.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124171323_SeedAllergyAndChronicDiseases")]
    partial class SeedAllergyAndChronicDiseases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AllergyUser", b =>
                {
                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<int>("allergiesId")
                        .HasColumnType("int");

                    b.HasKey("UsersId", "allergiesId");

                    b.HasIndex("allergiesId");

                    b.ToTable("UserAllergies", (string)null);
                });

            modelBuilder.Entity("App.Repository.Entities.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aspirin Alerjisi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Çilek Alerjisi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fıstık Alerjisi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gluten Alerjisi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "İyot Alerjisi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kabuklu Deniz Ürünleri Alerjisi"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kakao Alerjisi"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Küf Mantarı Alerjisi"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lateks Alerjisi"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Mantar Alerjisi"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Morfin Alerjisi"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Nikel Alerjisi"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Penisilin Alerjisi"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Polen Alerjisi"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Süt Ürünleri Alerjisi"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Soya Alerjisi"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Şeftali Alerjisi"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Tuzlu Su Balıkları Alerjisi"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Vanilya Alerjisi"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Yumurta Alerjisi"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Yer Fıstığı Alerjisi"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Çam Pollen Alerjisi"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Fındık Alerjisi"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Kaju Alerjisi"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Keten Tohumu Alerjisi"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Kuruyemiş Karışımı Alerjisi"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Lavanta Alerjisi"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Mercimek Alerjisi"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Mısır Alerjisi"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Okyanus Balıkları Alerjisi"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Pirinç Alerjisi"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Sarımsak Alerjisi"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Sedef Hastalığına Bağlı Alerji"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Somon Balığı Alerjisi"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Susam Alerjisi"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Tuzlu Su Karidesi Alerjisi"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Un Alerjisi"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Vanilya Fasulyesi Alerjisi"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Vişne Alerjisi"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Yaban Mersini Alerjisi"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Yeşil Mercimek Alerjisi"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Yosun Alerjisi"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Zencefil Alerjisi"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Zeytin Alerjisi"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Ev Tozu Akarı Alerjisi"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Kedi Tüyü Alerjisi"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Köpek Tüyü Alerjisi"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Saman Alerjisi"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Meyve Karışımı Alerjisi"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Sebze Karışımı Alerjisi"
                        });
                });

            modelBuilder.Entity("App.Repository.Entities.ChronicDiseasess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ChronicDiseasesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alzheimer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Akciğer Kanseri"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Anemi (Kronik)"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Astım"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Böbrek Yetmezliği"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Crohn Hastalığı"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Diyabet"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Epilepsi"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fibromiyalji"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Hiperkolesterolemi"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Hipertansiyon"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Hipotiroidi"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Hipertiroidi"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Kalp Yetmezliği"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Kanser"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Kolorektal Kanser"
                        },
                        new
                        {
                            Id = 17,
                            Name = "KOAH"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Koroner Arter Hastalığı"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Kronik Akciğer Hastalığı"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Kronik Böbrek Hastalığı"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Kronik Depresyon"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Kronik Enfeksiyonlar (HIV, Hepatit B/C)"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Kronik Göz Hastalıkları (Glokom, Katarakt)"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Kronik Karaciğer Hastalığı"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Kronik Migren"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Kronik Pancreatit"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Kronik Sinüzit"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Kronik Yorgunluk Sendromu"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Kronik Dermatolojik Hastalıklar"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Lupus"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Meme Kanseri"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Migren"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Multipl Skleroz (MS)"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Multiple Myeloma"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Obezite"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Osteoartrit"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Parkinson"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Prostat Kanseri"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Psoriatik Artrit"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Romatoid Artrit"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Siroz"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Uyku Apnesi"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Pulmoner Fibroz"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Kronik Anksiyete"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Kronik Böbrek Yetmezliği"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Kronik Karaciğer Yetmezliği"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Kronik Panik Bozukluğu"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Kronik Romatizmal Hastalıklar"
                        });
                });

            modelBuilder.Entity("App.Repository.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Registiration_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Registiration_number")
                        .IsUnique();

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("App.Repository.Entities.Frequency_of_use", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Frequency_of_uses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Günde 1 kez"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Günde 2 kez"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Günde 3 kez"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Haftada 1 kez"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Haftada 2 kez"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ayda 1 kez"
                        },
                        new
                        {
                            Id = 7,
                            Name = "İhtiyaç halinde"
                        });
                });

            modelBuilder.Entity("App.Repository.Entities.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Parol"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aspirin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "İbuprofen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nurofen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Amoksisilin"
                        });
                });

            modelBuilder.Entity("App.Repository.Entities.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Finish_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Frequency_of_useId")
                        .HasColumnType("int");

                    b.Property<bool>("IsTaked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Frequency_of_useId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("UserId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("App.Repository.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChronicDiseasessUser", b =>
                {
                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<int>("chronicDiseasessesId")
                        .HasColumnType("int");

                    b.HasKey("UsersId", "chronicDiseasessesId");

                    b.HasIndex("chronicDiseasessesId");

                    b.ToTable("UserChronicDiseases", (string)null);
                });

            modelBuilder.Entity("MedicineUser", b =>
                {
                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<int>("medicinesId")
                        .HasColumnType("int");

                    b.HasKey("UsersId", "medicinesId");

                    b.HasIndex("medicinesId");

                    b.ToTable("UserMedicines", (string)null);
                });

            modelBuilder.Entity("AllergyUser", b =>
                {
                    b.HasOne("App.Repository.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Repository.Entities.Allergy", null)
                        .WithMany()
                        .HasForeignKey("allergiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Repository.Entities.Reminder", b =>
                {
                    b.HasOne("App.Repository.Entities.Frequency_of_use", "Frequency_of_use")
                        .WithMany()
                        .HasForeignKey("Frequency_of_useId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Repository.Entities.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Repository.Entities.User", "User")
                        .WithMany("reminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frequency_of_use");

                    b.Navigation("Medicine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChronicDiseasessUser", b =>
                {
                    b.HasOne("App.Repository.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Repository.Entities.ChronicDiseasess", null)
                        .WithMany()
                        .HasForeignKey("chronicDiseasessesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicineUser", b =>
                {
                    b.HasOne("App.Repository.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Repository.Entities.Medicine", null)
                        .WithMany()
                        .HasForeignKey("medicinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Repository.Entities.User", b =>
                {
                    b.Navigation("reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
