// <auto-generated />
using System;
using App.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116203020_Mig2")]
    partial class Mig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AllergyUser", b =>
                {
                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<int>("allergiesId")
                        .HasColumnType("int");

                    b.HasKey("UsersId", "allergiesId");

                    b.HasIndex("allergiesId");

                    b.ToTable("UserAllergies", (string)null);
                });

            modelBuilder.Entity("App.Repository.Entities.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fıstık Alerjisi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gluten Alerjisi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Süt Ürünleri Alerjisi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Çilek Alerjisi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Yumurta Alerjisi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Polen Alerjisi"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kakao"
                        });
                });

            modelBuilder.Entity("App.Repository.Entities.ChronicDiseasess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ChronicDiseasesses");
                });

            modelBuilder.Entity("App.Repository.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Registiration_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Registiration_number")
                        .IsUnique();

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("App.Repository.Entities.Frequency_of_use", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Frequency_of_uses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Günde 1 kez"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Günde 2 kez"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Günde 3 kez"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Haftada 1 kez"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Haftada 2 kez"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ayda 1 kez"
                        },
                        new
                        {
                            Id = 7,
                            Name = "İhtiyaç halinde"
                        });
                });

            modelBuilder.Entity("App.Repository.Entities.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Parol"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aspirin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "İbuprofen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nurofen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Amoksisilin"
                        });
                });

            modelBuilder.Entity("App.Repository.Entities.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Finish_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Frequency_of_useId")
                        .HasColumnType("int");

                    b.Property<bool>("IsTaked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Frequency_of_useId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("UserId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("App.Repository.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChronicDiseasessUser", b =>
                {
                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<int>("chronicDiseasessesId")
                        .HasColumnType("int");

                    b.HasKey("UsersId", "chronicDiseasessesId");

                    b.HasIndex("chronicDiseasessesId");

                    b.ToTable("UserChronicDiseases", (string)null);
                });

            modelBuilder.Entity("MedicineUser", b =>
                {
                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<int>("medicinesId")
                        .HasColumnType("int");

                    b.HasKey("UsersId", "medicinesId");

                    b.HasIndex("medicinesId");

                    b.ToTable("UserMedicines", (string)null);
                });

            modelBuilder.Entity("AllergyUser", b =>
                {
                    b.HasOne("App.Repository.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Repository.Entities.Allergy", null)
                        .WithMany()
                        .HasForeignKey("allergiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Repository.Entities.Reminder", b =>
                {
                    b.HasOne("App.Repository.Entities.Frequency_of_use", "Frequency_of_use")
                        .WithMany()
                        .HasForeignKey("Frequency_of_useId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Repository.Entities.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Repository.Entities.User", "User")
                        .WithMany("reminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frequency_of_use");

                    b.Navigation("Medicine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChronicDiseasessUser", b =>
                {
                    b.HasOne("App.Repository.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Repository.Entities.ChronicDiseasess", null)
                        .WithMany()
                        .HasForeignKey("chronicDiseasessesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicineUser", b =>
                {
                    b.HasOne("App.Repository.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Repository.Entities.Medicine", null)
                        .WithMany()
                        .HasForeignKey("medicinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Repository.Entities.User", b =>
                {
                    b.Navigation("reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
